import { useEffect, useState } from 'react';
import { ArrowRight, Stethoscope, UserRound } from 'lucide-react';
import { Link } from 'react-router-dom';
import { toast } from 'react-hot-toast';
import api from '../../api/api';

const StatCard = ({ title, value, note, icon: Icon, tone }) => <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-sm font-medium text-slate-500">{title}</p><p className="mt-2 text-3xl font-semibold text-slate-900">{value}</p><p className="mt-2 text-xs text-slate-500">{note}</p></div><div className={`rounded-2xl p-3 ${tone}`}><Icon className="h-5 w-5" /></div></div></div>;

function AdminDashboard() {
  const [doctors, setDoctors] = useState([]);
  const [loading, setLoading] = useState(true);
  useEffect(() => { const load = async () => { try { const response = await api.get('/admin/doctors'); setDoctors(response.data?.doctors || []); } catch (error) { toast.error(error?.response?.data?.message || 'Unable to load dashboard data.'); } finally { setLoading(false); } }; load(); }, []);
  return <div className="space-y-6"><section className="rounded-3xl bg-gradient-to-br from-slate-950 via-slate-800 to-blue-900 p-7 text-white shadow-sm sm:p-8"><p className="text-sm font-semibold uppercase tracking-[.22em] text-blue-200">Clinic administration</p><div className="mt-3 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><h1 className="text-3xl font-semibold">Admin dashboard</h1><p className="mt-2 max-w-2xl text-sm text-slate-300">Maintain your doctor roster and coordinate availability from one workspace.</p></div><Link to="/admin/doctors" className="inline-flex w-fit items-center gap-2 rounded-xl bg-white px-4 py-2.5 text-sm font-semibold text-slate-900">Manage doctors <ArrowRight className="h-4 w-4" /></Link></div></section><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{loading ? Array.from({ length: 3 }).map((_, index) => <div key={index} className="h-36 animate-pulse rounded-2xl bg-slate-100" />) : <><StatCard title="Total doctors" value={doctors.length} note="Active provider profiles" icon={Stethoscope} tone="bg-blue-50 text-blue-600" /><StatCard title="Leave management" value="Ready" note="Create doctor leave entries" icon={UserRound} tone="bg-violet-50 text-violet-600" /></>}</div><section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between gap-4"><div><h2 className="text-xl font-semibold text-slate-900">Doctor roster</h2><p className="mt-1 text-sm text-slate-600">A quick view of your recently created doctor profiles.</p></div><Link to="/admin/doctors" className="text-sm font-semibold text-blue-700">View all</Link></div>{loading ? <div className="mt-5 h-40 animate-pulse rounded-2xl bg-slate-100" /> : doctors.length ? <div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{doctors.slice(0, 6).map((doctor) => <div key={doctor.id} className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><p className="font-semibold text-slate-900">{doctor.user?.name}</p><p className="mt-1 text-sm text-slate-600">{doctor.specialization}</p><p className="mt-3 text-xs font-medium text-slate-500">{doctor.slotDuration} minute slots</p></div>)}</div> : <div className="mt-5 rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-8 text-center text-sm text-slate-500">No doctors have been added yet.</div>}</section></div>;
}
export default AdminDashboard;
